### ISSUE TITLE
Question: Inherit default Xcode settings?

### ISSUE THREAD

**Issue by priteshshah1983** [jspahrsummers/xcconfigs#35]
Are these settings self-sufficient? Or is it recommended to use these settings along with the default settings that Xcode generates for a new project? If these are self-sufficient, I'm assuming the settings defined in Xcode should be deleted.

**Comment by fabb** [comment]
For our project, I removed most of Xcode's custom settings. Use the "Levels" view in Build Settings to see which settings come from Defaults/xcconfigs/Project/Target Settings. Watch out if you have non-default `ARCHS` and use cocoapods, as cocoapods ignores the archs configured in xcconfig files when creating the Pods project.

**Comment by priteshshah1983** [comment]
Thanks @fabb! If you can point me to an example for an iOS static library project, that would be great.
