### ISSUE TITLE
USE_CORRECT_VFMA_INTRINSICS

### ISSUE THREAD

**Issue by mathaeus** [jspahrsummers/xcconfigs#41]
Hi,

in the Xcode 6.3 release notes Apple states the following.

> ARM64 Intrinsics Changes
> • The argument ordering for the arm64 vfma/vfms lane intrinsics has changed. Since that change may not trigger compile-time errors but will break code at run-time, we are staging the transition to make it less risky.
> By default, the compiler will now warn about any use of those intrinsics and will retain the old behavior. As soon as possible, you should adopt the new behavior and define the USE_CORRECT_VFMA_INTRINSICS macro to 1 to inform the compiler of that. You can also define that macro to 0 to silence the warnings and keep the old behavior, but do not leave your code in that state for long, since we plan to remove support for the old behavior in a future release. (17964959)

I think it would be a good idea to include the `USE_CORRECT_VFMA_INTRINSICS=1` definition. Thoughts?

**Comment by jspahrsummers** [comment]
I'm not sure what the implications of that setting are, or how it would affect typical projects.

**Comment by fabb** [comment]
Any news on this?

**Comment by alanjrogers** [comment]
They mention that the old behaviour will be removed, given that this was several Xcode versions ago, they've possibly removed it by now.

**Comment by fabb** [comment]
Probably. I created a radar just yesterday to ask apple if this is still relevant. Let's see how they respond.

**Comment by fabb** [comment]
Response from Apple:

> - In Xcode 6.3, you could opt-in to the new (correct) behaviour by defining the USE_CORRECT_VFMA_INTRINSICS macro.
> - In Xcode 7.3, the compiler stopped looking at USE_CORRECT_VFMA_INTRINSICS, and the new (correct) behaviour was the only option.

So this issue can be closed.
