### ISSUE TITLE
BITCODE_GENERATION_MODE

### ISSUE THREAD

**Issue by conradev** [jspahrsummers/xcconfigs#45]
It would be great to see `BITCODE_GENERATION_MODE` set to `bitcode` for all relevant release binaries when `ENABLE_BITCODE` is set. Currently, default behavior in Xcode differs between building and archiving:

https://github.com/Carthage/Carthage/issues/535#issuecomment-142772958

**Comment by NachoSoto** [comment]
People are confirming that this works :tada: https://github.com/Carthage/Carthage/issues/535#issuecomment-143189623

**Comment by NachoSoto** [comment]
See #46
