### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by mgrebenets** [jspahrsummers/xcconfigs#47]
Any plans on supporting tricky case of CocoaPods integration?

I've been bitten by it recently and had to jump hoops and dance around xcconfig inheritance, utilise cocoapods post install hooks, etc. to get some setup working.

Would be nice to have pods supported in this repo.

**Comment by jspahrsummers** [comment]
I'm not sure where CocoaPods integration would make sense here, because it uses podspecs for configuration, not xcconfigs.

Regardless, I don't use CocoaPods, so I'm afraid that I'm not interested in supporting it. Sorry about that!
