### ISSUE TITLE
ENABLE_TESTABILITY

### ISSUE THREAD

**Issue by toshi0383** [jspahrsummers/xcconfigs#54]
Hi, I'm using in tvOS app.

I found that `ENABLE_TESTABILITY` is not configured.
Is there any reason for this, or do you want me to add that to Debug.xcconfig(YES) and Release.xcconfig(NO) ?

Also found these Xcode default settings are not set either.

```
CLANG_CXX_LANGUAGE_STANDARD="gnu++0x"
CLANG_CXX_LIBRARY="libc++"
GCC_NO_COMMON_BLOCKS=YES
MTL_ENABLE_DEBUG_INFO=  //YES in debug, NO in release
````

**Comment by diederich** [comment]
This should be fixed now.

**Comment by toshi0383** [comment]
Great 🚀
