### ISSUE TITLE
GCC_NO_COMMON_BLOCKS

### ISSUE THREAD

**Issue by calebd** [jspahrsummers/xcconfigs#55]
Xcode 7.2 warns that `GCC_NO_COMMON_BLOCKS` is not enabled.

**Comment by NachoSoto** [comment]
Weird, I haven't seen this warning myself (and I have that as the default `NO`). I'm not against adding this, but do you have any more info about why it would warn, despite the fact that it still defaults to `NO`?

**Comment by calebd** [comment]
It comes up as a "project warning" sometimes. I'll try to make it happen again and upload a screenshot.

**Comment by calebd** [comment]
<img width="603" alt="screen shot 2016-01-02 at 10 58 03 am" src="https://cloud.githubusercontent.com/assets/1761121/12075753/b6c0458e-b13f-11e5-8099-ce84ecc0caac.png">

**Comment by calebd** [comment]
The "Build Active Architecture Only" warning is also annoying since the resolved value is correct.

**Comment by NachoSoto** [comment]
Oh right, this only happens when upgrading from one version to another.
