### ISSUE TITLE
Needs an updated tag

### ISSUE THREAD

**Issue by Abizern** [jspahrsummers/xcconfigs#57]
The last tag was 0.8.1 back in May 2015

Carthage 0.12 seems to be having trouble resolving dependencies against "master" but I can't peg it to a tag because there is nothing more recent than 0.8.1.

**Comment by NachoSoto** [comment]
What problem does Carthage have with `master`? Do you have this in `Cartfile` or `Cartfile.private`?

**Comment by Abizern** [comment]
My Cartfile has:

```shell
github "jspahrsummers/xcconfigs" "master"
```

And all the dependencies which use xcconfigs have the same line, yet trying to do bootstrap or update gives:-

```shell
Could not pick a version for github "jspahrsummers/xcconfigs", due to mutually incompatible requirements:
	"d78854b22b9567e7f30d748bdd4966c86bcc93a5"
	"master"
```

Which is odd, because the sha is the latest commit on master.

**Comment by NachoSoto** [comment]
Any reason why you don't have this as a private dependency? Its version should not matter to the rest of dependencies.

**Comment by Abizern** [comment]
If it's a private dependency, how do enclosing projects know how to build the targets?

**Comment by NachoSoto** [comment]
By including `Carthage/Checkouts/xcconfigs` in your repo. A transitive dependencie does not need to carry this dependency or be concerned about versioning.

**Comment by erichoracek** [comment]
We do `git add --force Carthage/Checkouts/xcconfigs` despite having `Carthage/Checkouts` in the `.gitignore` since Carthage does not perform a checkout for dependencies.

**Comment by Abizern** [comment]
Interesting. I'll give it a try.

I still think an updated tag on this project is a good idea, though.

**Comment by NachoSoto** [comment]
I shipped a new version in any case: https://github.com/jspahrsummers/xcconfigs/releases/tag/0.9
