### ISSUE TITLE
New tag/release

### ISSUE THREAD

**Issue by erichoracek** [jspahrsummers/xcconfigs#72]
Hoping for a new tag, specifically with the `CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION` warning that was added somewhat recently. Thanks!

**Comment by fabb** [comment]
It seems like that warning was removed in Xcode 8.

**Comment by erichoracek** [comment]
This warning is still working for us in Xcode 8—it produces new warnings when enabled on a new project.

Here's an example:

![error](https://cloud.githubusercontent.com/assets/438313/22072795/4eda54c8-dd58-11e6-912a-96c48d5a00f6.png)

**Comment by erichoracek** [comment]
We have noticed a bug in Xcode 8 where the project must be reopened for `xcconfig` based settings to take effect—perhaps this is what you experience?

**Comment by fabb** [comment]
Interesting. Maybe it was the restart issue. But the setting also does not appear in the Xcode build settings pane anymore (just as user defined setting if set), which seems to suggest that it's no longer supported.

**Comment by diederich** [comment]
There is a new tag! 🎉
