### ISSUE TITLE
Add -Wpartial-availability

### ISSUE THREAD

**Issue by fabb** [jspahrsummers/xcconfigs#75]
http://stackoverflow.com/a/34040901/354018

**Comment by diederich** [comment]
Do you think this should still be enabled after Xcode 9's CLANG_WARN_UNGUARDED_AVAILABILITY?

**Comment by fabb** [comment]
#78

**Comment by fabb** [comment]
> Do you think this should still be enabled after Xcode 9's CLANG_WARN_UNGUARDED_AVAILABILITY?

Good catch, no according to https://reviews.llvm.org/D23003:

> `-Wpartial-availability` is now an alias of `-Wunguarded-availability`
