### ISSUE TITLE
Add CLANG_WARN_OBJC_LITERAL_CONVERSION

### ISSUE THREAD

**Issue by fabb** [jspahrsummers/xcconfigs#77]
New in Xcode 9

**Comment by diederich** [comment]
Seems like this becomes enabled via the CLANG_WARN_OBJC_LITERAL_CONVERSION which is already set.

<img width="824" alt="screen shot 2017-06-06 at 14 45 46" src="https://user-images.githubusercontent.com/61170/26853453-f48964be-4ac6-11e7-9ea9-290ab7d2962c.png">

Do you wanna to explicitly set this?

**Comment by fabb** [comment]
> Do you wanna to explicitly set this?
Why not - doesn't hurt, and is more explicit and resilient against future changes of the default

**Comment by fabb** [comment]
done by #80
