### ISSUE TITLE
New release for Xcode 9

### ISSUE THREAD

**Issue by mattrubin** [jspahrsummers/xcconfigs#81]
There have been many changes since the 0.10 tag for Xcode 8: https://github.com/jspahrsummers/xcconfigs/compare/0.10...master

**Comment by diederich** [comment]
Yeah, guess that's a good call. @NachoSoto you did the last ones. Do you want to or should I look into it?

**Comment by diederich** [comment]
It might have worked...

**Comment by mattrubin** [comment]
It worked! Thanks, @diederich!
