### ISSUE TITLE
GCC_WARN_UNUSED_PARAMETER

### ISSUE THREAD

**Issue by fabb** [jspahrsummers/xcconfigs#87]
The warning `GCC_WARN_UNUSED_PARAMETER` could be added as well. iOS default is `NO`.

**Comment by diederich** [comment]
Right - I just looked over the list in Xcode and there are actually quite a few which we haven't overwritten with the Default Value (maybe ~10-20%). I'm not sure we should. What's your thought on which ones to overwrite, which ones to leave the default (which comes in handy, if Apple ever changes them BTW :-))

**Comment by fabb** [comment]
Personally I think it‘s nice to have all settings in xcconfigs, even when they overwrite defaults, since I can quickly find them and change them temporarily. But apart from that there‘s not much value in it. When Apple decides to change a default, it will have a good reason (if that ever happens).

**Comment by diederich** [comment]
Hey @fabb, thanks for the clarification!
My workflow is actually changing overwrites in the xcodeprojects, and the xcconfigs are basically my better "Apple-defaults".
I'd suggest we leave out defaults that we don't think should be changed, and focus on the stuff we think we know better 😆

**Comment by fabb** [comment]
Fine with me!

So back to `GCC_WARN_UNUSED_PARAMETER`: should we activate it? It might be annoying for a few unused parameters in delegate methods, but apart from that it helps to keep the code clean.

**Comment by diederich** [comment]
I just enabled it here for the fun of it, and I think it does not work well together with Objective-C. 
Combined with our Warnings-As-Errors, all those warnings become must-fixs. And given the parameter name often has information, it can't be removed, and commenting it with `/* name */` might be too tedious?
I do remember having it enabled for my C++ projects, and using the commenting style above - but the style looks off for me in Objective-C. I can't recall having it seen it before as well. 
Omitting the unused parameter names altogether looks to me even more off to me. :-)
I see those are mostly style arguments, but nevertheless, have you seen the commented / omitted Objective-C parameter names often?

**Comment by fabb** [comment]
I‘m not really sure in which cases you would like to keep unused parameters at all, do you have some examples?

Fyi you can use `__unused` to annotate unused parameters that should not trigger the warning.

**Comment by fabb** [comment]
Ok, no problem.

**Comment by argl304** [comment]
The warning GCC_WARN_UNUSED_PARAMETER could be added as well. iOS default is YES.
