### ISSUE TITLE
Xcode 10, swift 4.2.1

### ISSUE THREAD

**Issue by jeremiasdsa** [jspahrsummers/xcconfigs#90]
Hi, @jspahrsummers 

I'm getting this during "carthage update --platform iOS"

![Screen Shot 2019-03-15 at 6 04 52 PM](https://user-images.githubusercontent.com/9071775/54462028-16acfb80-474d-11e9-83e7-7e210d115788.png)

Any Idea of how to solve it?

**Comment by mattrubin** [comment]
Aside from the error message, are you having any trouble actually using these dependencies?

The message is correct: xcconfigs has no frameworks that Carthage can build. Instead, it supplies config files that are used when building other projects. If the other dependencies are building without error, you can safely ignore the warning about xcconfigs.

**Comment by jeremiasdsa** [comment]
Hi @mattrubin 

![Screen Shot 2019-03-15 at 6 48 10 PM](https://user-images.githubusercontent.com/9071775/54463880-48c15c00-4753-11e9-87c2-5d007ee2329f.png)

I'm getting this error

**Comment by mattrubin** [comment]
Is this the same project as before? It looks like you're including a new Carthage module now.

As far as I can tell, the Carthage module you're using is not open source, so I can't examine it to see how it is set up to use the xcconfigs, but this is definitely an issue with a project not correctly including its dependency on xcconfigs, and not an issue with xcconfigs itself.

One thing that may or may not help, depending on how the project is set up, is checking out nested git submodules by running:

``` 
git submodule update --init --recursive
```

As I said, the carthage module you're having trouble with isn't open source, so I can't help you if the above doesn't work. I would recommend contacting the person who created the `cloudia-message-processor-swift-ecr` project.

**Comment by jeremiasdsa** [comment]
Hi, @mattrubin 
I'm glade to have you giving me directions to solve the problem.

So, I consider that they are the same project, because I have a framework "A" using xcconfigs, framework "B" using framework A, and a main iOS application using framework B. 

On A and B, I'am able to run carthage update --platform iOS, even with xcconfigs warning.
But when I'm trying to run carthage update --platform iOS on main IOS app, I'm getting the message on figure 2. That's why I'm thinking that the error is related to xcconfigs. Because, using Xcode 9.0.1, there is no warnings.

**Comment by mattrubin** [comment]
@jeremiasdsa As I mentioned above, xcconfigs simply provides config files that are then used by other projects. Since the error messages in your screenshot are about the build system being unable to open the xcconfig files, I suspect the issue is *not* with the xcconfig files, but is with the project attempting to use them. It might also be a Carthage-related issue.

**Comment by diederich** [comment]
Looks like this has been resolved. Thanks @mattrubin!

For reference Carthage's message of "xcconfigs doesn't have a framework to build" is correct - There is no framework to build for xcconfigs
