### ISSUE TITLE
Update with new warnings

### ISSUE THREAD

**Issue by diederich** [jspahrsummers/xcconfigs#92]
Given Xcode 10.2 was released I browsed though the warnings list today. And found some new things (stuff I haven't seen before):

```
// Warn about assigning integer constants to enum values that are out of the range of the enumerated type.
CLANG_WARN_ASSIGN_ENUM = YES

// Warns when a quoted include is used instead of a framework style include in a framework header.
CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES

// Warn when a source file does not end with a newline.
GCC_WARN_ABOUT_MISSING_NEWLINE = YES

// Check for Grand Central Dispatch idioms that may lead to poor performance.
CLANG_ANALYZER_GCD_PERFORMANCE = YES

// Warn about implicit ownership types on Objective-C object references as out parameters. For example, declaring a parameter with type `NSObject**` will produce a warning because the compiler will assume that the out parameter's ownership type is `__autoreleasing`
CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE = YES
```

Following seem to be gone as of Xcode 10.2?
```
CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION
CODE_SIGNING_REQUIRED
```

Will have a more closer look tomorrow, but those came up first. 
Any other?

**Comment by fabb** [comment]
From the release notes, these also look interesting:
• `-Wframework-include-private-from-public`
• `-Watimport-in-framework-header`

I haven‘t yet looked up the config names of these yet.

**Comment by diederich** [comment]
> The use of @import in framework headers prevent headers being used without modules. A new diagnostic detects the use of @import in framework headers when you pass the -fmodules flag. The diagnostic is OFF by default in clang and is controlled using the -Watimport-in-framework-header flag. (39192894)

**Comment by diederich** [comment]
> Warns when an atomic is used with an implicitly sequentially-consistent memory order, instead of explicitly specifying memory order.
> CLANG_WARN_ATOMIC_IMPLICIT_SEQ_CST

**Comment by diederich** [comment]
@fabb 
> -Wframework-include-private-from-public
Seems to be on by default, and I couldn't find it in Xcode. 

> -Watimport-in-framework-header
I also couldn't find this one in Xcode. 

While we could enable them via the WARNING_CFLAGS, it's harder for users to disable them on the per project basis. I'd skip them for now.
